#!/bin/bash

COMPOSE_FILE="/opt/httpd/docker-compose.yml"

docker_compose_up() {
    docker compose --profile $1 -f $COMPOSE_FILE up -d
}

docker_compose_down() {
    docker compose --profile $1 -f $COMPOSE_FILE down
}

docker_compose_restart() {
    docker_compose_down $1
    docker_compose_up $1
}

# if 1st arg is pw and 2nd arg is up then pw profile will be used, if it's down then down it
if [ "$1" == "pw" ]; then
    if [ "$2" == "up" ]; then
        docker_compose_up pw
    elif [ "$2" == "down" ]; then
        docker_compose_down pw
    elif [ "$2" == "restart" ]; then
        docker_compose_restart pw
    fi
    exit 0
fi

# if arg is openvpn then openvpn profile will be used
if [ "$1" == "openvpn" ]; then
    if [ "$2" == "up" ]; then
        docker_compose_up openvpn
    elif [ "$2" == "down" ]; then
        docker_compose_down openvpn
    elif [ "$2" == "restart" ]; then
        docker_compose_restart openvpn
    fi
    exit 0
fi

# if arg is web then web profile will be used
if [ "$1" == "web" ]; then
    if [ "$2" == "up" ]; then
        docker_compose_up web
    elif [ "$2" == "down" ]; then
        docker_compose_down web
    elif [ "$2" == "restart" ]; then
        docker_compose_restart web
    fi
    exit 0
fi

# if arg is gaia then gaia profile will be used, if it's down then down
if [ "$1" == "gaia" ]; then
    if [ "$2" == "up" ]; then
        docker_compose_up gaia
    elif [ "$2" == "down" ]; then
        docker_compose_down gaia
    elif [ "$2" == "restart" ]; then
        docker_compose_restart gaia
    fi
    exit 0
fi

# if arg is down then down them all one by one
if [ "$1" == "up" ]; then
    docker_compose_up pw
    docker_compose_up openvpn
    docker_compose_up web
    docker_compose_up gaia
    exit 0
elif [ "$1" == "down" ]; then
    docker_compose_down pw
    docker_compose_down openvpn
    docker_compose_down web
    docker_compose_down gaia
    exit 0
elif [ "$1" == "restart" ]; then
    docker_compose_restart pw
    docker_compose_restart openvpn
    docker_compose_restart web
    docker_compose_restart gaia
    exit 0
fi


echo "Usage: $0 {pw|openvpn|web|gaia} {up|down|restart}"
exit 1

