version: '3'

services:
  ollama:
    image: ollama/ollama
    restart: always
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    depends_on:
      - open-webui

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    volumes:
      - open-webui:/app/backend/data
#      - open-webui-data:/app/backend/data
    ports:
      - "3000:8080"
    environment:
      - HOST_Gateway=host.docker.internal

#  stable-diffusion-webui:
#    build: .
#    image: stable-diffusion-webui1
#    ports:
#      - "7860:7860"
#    command: "./webui.sh --listen --api --skip-torch-cuda-test"


volumes:
  ollama:
  open-webui:
